name: Producción - Crear Rama Release y Mezclar con Main

on:
  push:
    branches:
      - develop

jobs:
  release:
    name: Crear rama release y mezclar a main
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del Repositorio
      uses: actions/checkout@v2

    - name: Crear Rama Release y subirla a remoto
      run: |
        git switch -c release/${{ github.run_number }}
        git push -f -u origin release/${{ github.run_number }}

    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'

    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests

    - name: Mezcla release -> main
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: release/${{ github.run_number }}
        target-branch: main