name: Producción - Crear Rama Release y Mezclar con Main

on:
  push:
    branches:
      - develop

jobs:
  release:
    name: Crear Rama Release y Mezclar con Main
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del Repositorio
      uses: actions/checkout@v2

    - name: Crear Rama Release
      run: git checkout -b release/${{ github.run_number }}

    - name: Configurar Entorno de Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Correr Pruebas
      run: python -m unittest discover -v tests/

    - name: Mezclar con Rama Main
      if: success()
      run: |
        git fetch --all
        git branch
        git checkout origin/main
        git merge --no-ff release/${{ github.run_number }}
        git push origin main