name: Producción - Crear Rama Release y Mezclar con Main

on:
  push:
    branches:
      - develop

jobs:
  release:
    name: Crear Rama Release y Mezclar con Main
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del Repositorio
      uses: actions/checkout@v2

    - name: Crear Rama Release
      run: git switch -c release/${{ github.run_number }}

    - name: Configurar Entorno de Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Mezclar con Rama Main
      if: success()
      run: |
        git fetch origin main:main
        git switch main
        git pull origin main
        git switch main
        git merge --no-ff release/${{ github.run_number }}
        git push origin main